train: 
  seed: 1234
  output_directory: 'training_log'
  output_name: 'test2'
  data_path: '/ssd/vox1'
  training_files: '/home/miseul/cousework/selectra/filelists/vox1_train.txt'
  validation_files: '/home/miseul/cousework/selectra/filelists/vox1_val.txt'
  batch_size: 64
  selectra_checkpoint: 252000  

data:
  sampling_rate: 16000

model:
  n_symbols: 27 # alphabet (26) + blank (1)
  hidden_dim: 512
  enc_hidden_dim: 768

optimization:
  lr: 0.00005
  grad_clip_thresh: 5.0
  accumulation: 4
  iters_per_validation: 1000
  iters_per_checkpoint: 1000
  train_steps: 200000
