train: 
  seed: 1234
  output_directory: 'training_log'
  output_name: 'test_zerobias'
  data_path: '/ssd/KeywordSpotting'
  training_files: '/home/miseul/cousework/selectra/filelists/keyword_train.txt'
  validation_files: '/home/miseul/cousework/selectra/filelists/keyword_val.txt'
  batch_size: 2
  selectra_checkpoint: 252000  

data:
  sampling_rate: 16000

model:
  n_symbols: 27 # alphabet (26) + blank (1)
  hidden_dim: 512
  enc_hidden_dim: 768

optimization:
  lr: 0.00005
  grad_clip_thresh: 1.0
  accumulation: 100
  iters_per_validation: 100
  iters_per_checkpoint: 10000
  train_steps: 200000
