train: 
  seed: 1234
  output_directory: 'training_log'
  output_name: 'base'
  data_path: '/ssd/LibriSpeech/train-clean-100'
  training_files: '/home/miseul/cousework/selectra/filelists/libri_train.txt'
  validation_files: '/home/miseul/cousework/selectra/filelists/libri_val.txt'
  batch_size: 16

data:
  sampling_rate: 16000

model:
  n_symbols: 27 # alphabet (26) + blank (1)
  hidden_dim: 512

optimization:
  lr: 0.00005
  grad_clip_thresh: 1.0
  accumulation: 10
  iters_per_validation: 10
  iters_per_checkpoint: 10000
  train_steps: 200000
